coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        target: auto
        informational: false

ignore:
  - "core/src/main/com/invenit/bacillus/ui/**"
