sonar.projectKey=lamao_bacillus
sonar.organization=lamao
sonar.host.url=https://sonarcloud.io

sonar.sources=core/src/main,desktop/src/main
sonar.tests=core/src/test

sonar.coverage.jacoco.xmlReportPaths=core/build/reports/jacoco/test/jacocoTestReport.xml
